package com.desafio.desafio.exception;

public class RecordFoundException extends RuntimeException {
    
    public RecordFoundException(String documento) {
        super("JÃ¡ existe um cliente registrado com o documento: " + documento);
    }
}
